# Load memory monitoring library
library(pryr)

# Set number of bootstrap iterations
B <- 1000

# Record start time and memory usage
start_time <- Sys.time()
mem_before <- mem_used()

# Read data generated by Go
data <- read.csv("original_data.csv", header = FALSE)
thisSample <- data$V1
n <- length(thisSample)

# Perform bootstrap sampling
bootstrapMedians <- numeric(B)
set.seed(9999)  # Ensure reproducibility

for (b in 1:B) {
  resample <- sample(thisSample, n, replace = TRUE)
  bootstrapMedians[b] <- median(resample)
}

# Calculate standard error (standard deviation of bootstrap medians)
se_median <- sd(bootstrapMedians)

# Record end time and memory usage
end_time <- Sys.time()
mem_after <- mem_used()

# Calculate total time and memory difference
duration_ms <- round(as.numeric(difftime(end_time, start_time, units = "secs")) * 1000, 1)
mem_diff <- mem_after - mem_before

# Print output
cat("Estimated SE of Median (R):", round(se_median, 5), "\n")
cat("Total runtime:", duration_ms, "ms\n")
cat("Total memory used:", format(mem_diff, units = "auto"), "\n")
